services:
  build: &base
    build: .
    image: ghcr.io/carapace-sh/carapace
    command: sh -c 'cd /carapace/example && go build -buildvcs=false .'
    user: 1000:1000
    environment:
      TARGET: /carapace/example/example
    volumes:
      - '.:/carapace/'

  bash:
    <<: *base
    command: bash

  ble:
    <<: *base
    command: bash
    environment:
      BLE: 1
      TARGET: /carapace/example/example

  elvish:
    <<: *base
    command: elvish

  fish:
    <<: *base
    command: fish
  
  ion:
    <<: *base
    command: ion
  
  nushell:
    <<: *base
    command: nu
  
  oil:
    <<: *base
    command: osh --completion-display minimal

  powershell:
    <<: *base
    command: pwsh
  
  tcsh:
    <<: *base
    command: tcsh

  xonsh: 
    <<: *base
    command: xonsh

  zsh:
    <<: *base
    command: zsh

  test:
    <<: *base
    working_dir: /carapace
    command: fish -c "go test -v ./..."

  vhs:
    <<: *base
    working_dir: /carapace/docs/src/development/vhs
    command: bash -c "ls -d */ | xargs -I'{}' bash -c \"cd {};ls *.tape | xargs -n1 vhs\""

volumes:
  go:
