FROM golang

RUN curl https://dl.elv.sh/linux-amd64/elvish-v0.14.1.tar.gz | tar -xvz \
 && mv elvish-* /usr/local/bin/elvish

ENV PS1=$'%{\e[0;36m%}carapace %{\e[0m%}'

RUN ln -s /carapace/example/example /usr/local/bin/example

RUN mkdir -p /root/.elvish/lib \
 && echo "\
/carapace/example/example _carapace elvish > /root/.elvish/lib/example.elv\n\
use example" \
  > /root/.elvish/rc.elv

ENTRYPOINT [ "elvish" ]

