package testfiles

//go:generate touch -- -_minus_prefix.txt
//go:generate touch -- ampersand_&.txt
//go:generate touch -- angle-bracket_left_<.txt
//go:generate touch -- angle-bracket_right_>.txt
//go:generate touch -- angle-bracket_both_<>.txt
//go:generate touch -- backslash_linebreak_\n.txt
//go:generate touch -- backslash_tab_\t.txt
//go:generate touch -- backslash_single_\.txt
//go:generate touch -- backslash_double_\\.txt
//go:generate touch -- backtick_single_`.txt
//go:generate touch -- backtick_double_``.txt
//go:generate touch -- colon_:.txt
//go:generate touch -- curly-bracket_left_{.txt
//go:generate touch -- curly-bracket_right_}.txt
//go:generate touch -- curly-bracket_both_{}.txt
//go:generate touch -- dollar_single_$.txt
//go:generate touch -- dollar_round_$().txt
//go:generate touch -- "dollar_curly_${}.txt"
//go:generate touch -- quote_single_'.txt
//go:generate touch -- quote_double_".txt
//go:generate touch -- quote_both_'".txt
//go:generate touch -- hash_#.txt
//go:generate touch -- pipe_|.txt
//go:generate touch -- question_?.txt
//go:generate touch -- round-bracket_left_(.txt
//go:generate touch -- round-bracket_right_).txt
//go:generate touch -- round-bracket_both_().txt
//go:generate touch -- semicolon_;.txt
//go:generate touch -- single-quote_'.txt
//go:generate touch -- "space_ .txt"
//go:generate touch -- square-bracket_left_[.txt
//go:generate touch -- square-bracket_right_].txt
//go:generate touch -- square-bracket_both_[].txt
//go:generate touch -- "star_*.txt"
//go:generate touch -- "star_*_match.txt"
//go:generate touch -- ~_tilde_prefix.txt
//go:generate touch -- ~_tilde_prefix_pipe_|.txt
