#!/bin/bash -i
#set -x
source <(example _carapace bash)
COMP_LINE="$1"
COMP_POINT=${#1}
COMP_WORDS=($COMP_LINE'')
COMP_CWORD=$((${#COMP_WORDS[@]}-1))

_example_completion
( IFS=$'\n'; echo "${COMPREPLY[*]}" )
