FROM golang

RUN apt-get update \
 && apt-get install -y python3-pip

RUN pip3 install --no-cache-dir --disable-pip-version-check xonsh \
 && ln -s $(which xonsh) /usr/bin/xonsh


RUN mkdir -p ~/.config/xonsh \
 && echo "\n\
\$COMPLETIONS_CONFIRM=True\n\
\$PROMPT='carapace '\n\
exec(\$(example _carapace xonsh))" \
  > ~/.config/xonsh/rc.xsh

RUN ln -s /carapace/example/example /usr/local/bin/example

ENTRYPOINT [ "xonsh" ]

