[book]
authors = ["rsteube"]
language = "en"
multilingual = false
src = "src"
title = "carapace"
description = "A multi-shell completion library."

[output.html]
default-theme = "Latte"
preferred-dark-theme = "Mocha"
additional-css = ["asciinema/asciinema-player.css", "./theme/catppuccin.css"]
additional-js = ["asciinema/asciinema-player.min.js", "asciinema/load.js"]
git-repository-url = "https://github.com/carapace-sh/carapace"
edit-url-template = "https://github.com/carapace-sh/carapace/edit/master/docs/{path}"

[output.html.fold]
enable = true

[output.linkcheck]
follow-web-links = true
exclude = [ 'gnu\.org', '\./.+/out/.+\.gif', 'go\.dev', 'microsoft\.com']
