name: Doc

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: shallow clone
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: build
        run: |
          cd example
          go build

      - uses: actions/upload-artifact@v4
        with:
          name: example
          path: example/example
          retention-days: 1


  word:               {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: word}}
  nospace:            {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: nospace}}
  doubleQuote:        {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: doubleQuote}}
  doubleQuoteOpen:    {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: doubleQuoteOpen}}
  doubleQuotePartial: {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: doubleQuotePartial}}
  singleQuote:        {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: singleQuote}}
  singleQuoteOpen:    {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: singleQuoteOpen}}
  singleQuotePartial: {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: singleQuotePartial}}
  escape:             {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: escape}}
  redirect:           {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: redirect}}
  special:            {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: special}}
  specialDoubleQuote: {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: specialDoubleQuote}}
  specialSingleQuote: {needs: build, uses: ./.github/workflows/vhs-template.yml, with: {topic: specialSingleQuote}}

  doc:
    needs:
      - word
      - nospace
      - doubleQuote
      - doubleQuoteOpen
      - doubleQuotePartial
      - singleQuote
      - singleQuoteOpen
      - singleQuotePartial
      - escape
      - redirect
      - special
      - specialDoubleQuote
      - specialSingleQuote
    runs-on: ubuntu-latest
    container: ghcr.io/carapace-sh/mdbook
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          key: linkcheck
          path: docs/book/linkcheck

      - uses: actions/download-artifact@v4
        with:
          path: docs/src/development/vhs/

      - name: Display structure of downloaded files
        run: ls -R docs/src/development/vhs/

      - name: "build docs"
        run: |
            mdbook build docs

      - name: "push gh-pages"
        if: github.ref == 'refs/heads/master'
        run: |
            cd docs/book/html/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/carapace-sh/carapace.git master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
