name: Go

on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rsteube/carapace
    steps:
      - name: shallow clone
        uses: actions/checkout@v2
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: deep clone
        uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      
      - name: Generate
        run: go generate ./...

      - name: Test
        run: go test -v -coverprofile=profile.cov ./... ./example-nonposix/...

      - name: "Check formatting"
        run: '[ "$(gofmt -d -s . | tee -a /dev/stderr)" = "" ]'

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}