name: vhs template

on:
  workflow_call:
    inputs:
      topic:
        required: true
        type: string

jobs:
  vhs:
    runs-on: ubuntu-latest
    container: ghcr.io/carapace-sh/carapace
    steps:
      - name: shallow clone
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: example
          path: /usr/local/bin/

      - run: chmod +x /usr/local/bin/example

      - name: vhs
        run: | 
          cd docs/src/development/vhs/${{ inputs.topic }}
          ls *.tape | xargs -n1 vhs

      - uses: actions/upload-artifact@v4
        with:
          name: vhs-${{ inputs.topic }}
          path: docs/src/development/vhs/${{ inputs.topic }}/out
          retention-days: 1

      - name: check
        run: |
          git status --porcelain
          [ -z "$(git status --porcelain)" ] # clean workspace unless .ascii files changed

